name: Testing Deployement

on:
  push:
    branches:
      - github-ci

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update ubuntu package lists
        run: sudo apt-get update -y
      - name: Install shunit2
        run: sudo apt-get install shunit2 -y
      - name: Install check
        run: sudo apt-get install check -y
      - name: Build project
        run: make all
      - name: Run Test Suite
        run: make test
